title: "PoC: Schema checkers"
description: "Based on Python libraries"
baseurl: "/poc-schema-checks"
url: "https://tisnik.github.io"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/tisnik/poc-schema-checks"

footer_content: "Copyright &copy; 2020 Pavel Tisnovsky</a>"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

theme: jekyll-theme-leap-day
